### ISSUE TITLE
Cannot compile angular universal application with Debug enabled

### ISSUE THREAD

**Issue by massimilianobraglia** [jymfony/angular-universal-bundle#1]
Hey there!
While trying to build an angular application with debug enabled the following error is throwed:
```sh
Angular universal - compile
===========================


                                                                      
  [TypeError]                                                         
  Cannot add property _indicatorUpdateTime, object is not extensible  
                                                                      

Exception trace:
   ProgressIndicator.start() at /var/www/app/node_modules/@jymfony/console/src/Helper/ProgressIndicator.js:107
   JymfonyStyle.progressStart() at /var/www/app/node_modules/@jymfony/console/src/Style/JymfonyStyle.js:241
   BuildCommand.execute() at /var/www/app/node_modules/@jymfony/angular-universal-bundle/src/Command/BuildCommand.js:40
   BuildCommand.run() at /var/www/app/node_modules/@jymfony/console/src/Command/Command.js:198
   process.runNextTicks [as _tickCallback]() at internal/process/task_queues.js:52
   Function.Module.runMain() at internal/modules/cjs/loader.js:880
   ?() at internal/main/run_main_module.js:21

angular:build-universal [-o|--outDir OUTDIR] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [--e|--env ENV] [--no-debug] [--] <command>
```

I think that this is caused by this line https://github.com/jymfony/util/blob/master/lib/Object/serialize.js#L213 in the Jymfony's utils serializer

**Comment by alekitto** [comment]
Hi @massimilianobraglia.
Every object loaded by the autoloader component is closed to extensions after its construction while in debug mode. This ensures that no property is added/removed after the constructor call while developing or testing the application. [Here's the preventExtensions call](https://github.com/jymfony/jymfony/blob/0eb732c8ee0505367dc77c66bb9afd3ead9ed8c9/src/Component/Autoloader/src/Namespace.js#L247).

Regarding this error, the `_indicatorUpdateTime` is probably not defined while constructing the `ProgressIndicator` object. I'm currently working to add this property to the constructor and add the tests for that class (which currently lacks of tests).

**Comment by massimilianobraglia** [comment]
Hey there @alekitto! Thanks for the clarification.
Makes sense :)

Glad to hear that you are aware about this one. Closing this issue

**Comment by alekitto** [comment]
FYI: has been fixed in https://github.com/jymfony/jymfony/commit/b519f675e8abcab63caed5f42694033f725558e5
